on:
  push:
    branches: [main]
  pull_request:
name: CI
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-25.08
      options: --privileged
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    steps:
    - uses: actions/checkout@v6
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: dosbox.flatpak
        manifest-path: com.dosbox.DOSBox.yaml
        cache-key: flatpak-builder-${{ github.sha }}
